2016/05/12 21:38:50 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: update
2016/05/12 21:38:51  ▸    Error: Unexpected flag --background
 ▸    Usage: heroku update [CHANNEL]
 ▸    This command does not take any flags.
 ▸    
 ▸    See more information with heroku update --help
2016/05/12 21:38:51 triggering background update
2016/05/12 21:38:51 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: update
2016/05/12 21:39:02 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: version
2016/05/12 21:39:02 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: commands
2016/05/12 21:39:02 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: create
2016/05/12 21:39:03 Error: Expected response to be successful, got 422
    at Request.handleFailure (/home/nitrous/.local/share/heroku/cli/lib/node_modules/heroku-client/lib/request.js:285:9)
    at /home/nitrous/.local/share/heroku/cli/lib/node_modules/heroku-client/lib/request.js:164:14
    at IncomingMessage.<anonymous> (/home/nitrous/.local/share/heroku/cli/lib/node_modules/heroku-client/lib/request.js:393:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2016/05/12 21:39:03 {"id":"invalid_params","message":"Name is already taken"}
2016/05/12 21:39:22 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: version
2016/05/12 21:39:22 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: commands
2016/05/12 21:39:22 heroku-cli/5.1.7-0de2607 (linux-amd64) go1.6.2 /home/nitrous/.local/share/heroku/cli/bin/heroku cmd: create
